version: '3.4'

volumes:
  mysite.mysqldb.volume:
    name: mysite.mysqldb.volume
  mysite.postgresdb.volume:
    name: mysite.postgresdb.volume

services:
  nginx:
    image: nginx:1.18
    container_name: mysite.nginx
    ports:
      - "8003:8003"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./static:/static
      - ./dist:/var/www/html
    depends_on:
      - web

  mysqldb:
    image: mysql:5.7
    container_name: mysite.mysqldb
    ports:
      - 33060:33060
    environment:
      MYSQL_ROOT_PASSWORD: mysitepass
      TZ: 'Asia/Shanghai'
    volumes:
      - mysite.mysqldb.volume:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d/

  postgresql:
    image: postgres
    container_name: mysite.postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "mysite"
      POSTGRES_USER: "mysiteuser"
      POSTGRES_PASSWORD: "mysitepass"
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    volumes:
      - mysite.postgresdb.volume:/var/lib/postgresql
      - ./postgresql/create_init.sh:/docker-entrypoint-initdb.d/create_init.sh

  web:
    build: ./web
    container_name: mysite.web
    command: ["/wait-for-it.sh", "mysqldb:3306", "--", "uwsgi", "--socket", ":8001", "--module", "mysite.wsgi"]
    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh
      - ./src:/code
      - ./config.json:/code/dongtai_agent_python/config.json
      - ./static:/static
    expose:
      - "8001"
    depends_on:
      - mysqldb
