version: '3.4'

volumes:
  mysite.mysqldb.volume:
    name: mysite.mysqldb.volume
  mysite.postgresdb.volume:
    name: mysite.postgresdb.volume

services:
  nginx:
    image: nginx:1.18
    container_name: mysite.nginx
    ports:
      - "8003:8003"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params

      - ./dist:/var/www/html
    depends_on:
      - djangoweb

  mysqldb:
    image: mysql:5.7
    container_name: mysite.mysqldb
    ports:
      - 33060:33060
    environment:
      MYSQL_ROOT_PASSWORD: mysitepass
      TZ: 'Asia/Shanghai'
    volumes:
      - mysite.mysqldb.volume:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d/
  mongo:
    image: mongo
    container_name: mysite.mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: "mysiteuser"
      MONGO_INITDB_ROOT_PASSWORD: "mysitepass"
  postgresql:
    image: postgres
    container_name: mysite.postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "mysite"
      POSTGRES_USER: "mysiteuser"
      POSTGRES_PASSWORD: "mysitepass"
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    volumes:
      - mysite.postgresdb.volume:/var/lib/postgresql
      - ./postgresql/create_init.sh:/docker-entrypoint-initdb.d/create_init.sh

  djangoweb:
    build:
      context: .
      dockerfile: ./djangosrc/Dockerfile
    container_name: mysite.djangoweb
    command: ["/wait-for-it.sh", "mysqldb:3306", "--", "uwsgi", "--socket", ":8001", "--module", "mysite.wsgi"]
    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh
      - ./djangosrc:/code
      - ./sqlite/db.sqlite3:/code/db.sqlite3
    environment:
      AUTO_CREATE_PROJECT: 1
      PROJECT_VERSION: ${PROJECT_VERSION:-v1.0.0}
      ENGINE_NAME: "github-vul-test-django"
    expose:
      - "8001"
    depends_on:
      - mysqldb
      - postgresql

  flaskweb:
    build:
      context: .
      dockerfile: ./flasksrc/Dockerfile
    container_name: mysite.flaskweb
    command: ["/wait-for-it.sh", "mysqldb:3306", "--", "python","-u","-m","flask","run","-h","0.0.0.0"]
    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh
      - ./flasksrc:/code
      - ./sqlite/db.sqlite3:/code/db.sqlite3
    environment:
      FLASK_APP: app.py
      AUTO_CREATE_PROJECT: 1
      PROJECT_VERSION: ${PROJECT_VERSION:-v1.0.0}
      ENGINE_NAME: "github-vul-test-flask"
    expose:
      - "5000"
    depends_on:
      - mysqldb
      - postgresql
    restart: always
